name: appwrite_function
description: Dart starter for Appwrite function.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  dart_appwrite: ^7.1.0
      
dev_dependencies:
  lints: ^2.0.1
